"""
Generic main trading bot - DO NOT EDIT THIS FILE

To change the broker or strategy, edit config/trading_config.py instead.
This main.py will automatically use whatever broker and strategy you configure.
"""
import asyncio
import logging
import signal
import sys
from pathlib import Path
from datetime import datetime

from config.settings import WS_URL, SYMBOLS
from config.trading_config import (
    get_broker_factory,
    get_strategy_factory,
    RESOLUTION,
    THROTTLE,
    LOG_LEVEL,
    LOG_TO_FILE,
    LOG_TO_CONSOLE,
)
from data.webscoket import candlestick_stream
from engine.runner import MultiSymbolEngine

# ============================================================================
# SETUP LOGGING
# ============================================================================
log_dir = Path("logs")
log_dir.mkdir(exist_ok=True)

timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
log_file = log_dir / f"trading_bot_{timestamp}.log"

logger = logging.getLogger("trading_bot")
logger.setLevel(getattr(logging, LOG_LEVEL))
logger.handlers.clear()

if LOG_TO_FILE:
    file_handler = logging.FileHandler(log_file, encoding="utf-8")
    file_handler.setLevel(getattr(logging, LOG_LEVEL))
    file_formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    file_handler.setFormatter(file_formatter)
    logger.addHandler(file_handler)

if LOG_TO_CONSOLE:
    console_handler = logging.StreamHandler(sys.stdout)
    console_handler.setLevel(getattr(logging, LOG_LEVEL))
    console_formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')
    console_handler.setFormatter(console_formatter)
    logger.addHandler(console_handler)


# ============================================================================
# GLOBAL STATE
# ============================================================================
broker = None


def signal_handler(sig, frame):
    """Handle Ctrl+C gracefully - log statistics before exiting."""
    if broker:
        logger.info("Shutting down... Printing final statistics:")
        broker.print_statistics()
    sys.exit(0)


async def main() -> None:
    """
    Generic trading bot that uses configured broker and strategy.
    """
    global broker
    
    signal.signal(signal.SIGINT, signal_handler)
    
    # Get broker and strategy factories from config
    broker_factory = get_broker_factory()
    strategy_factory = get_strategy_factory()
    
    # Initialize broker
    broker = broker_factory()
    
    # Log startup information
    logger.info("=" * 80)
    logger.info("TRADING BOT STARTED")
    logger.info("=" * 80)
    logger.info(f"Broker: {broker.__class__.__name__}")
    logger.info(f"Initial Balance: ${broker.initial_balance:.2f}")
    logger.info(f"Symbols ({len(SYMBOLS)}): {SYMBOLS}")
    logger.info(f"Resolution: {RESOLUTION}")
    logger.info(f"Strategy: {strategy_factory().__class__.__name__}")
    logger.info(f"Throttle: {THROTTLE}s")
    logger.info(f"Press Ctrl+C to stop and view statistics")
    logger.info("=" * 80)
    
    # Create multi-symbol engine
    engine = MultiSymbolEngine(
        strategy_factory=strategy_factory,
        broker=broker,
        resolution=RESOLUTION,
        throttle=THROTTLE
    )
    
    # Track statistics update interval
    import time
    last_stats_print = time.time()
    stats_interval = 300  # Print stats every 5 minutes
    
    # Subscribe to candle stream
    try:
        async for candle in candlestick_stream(WS_URL, SYMBOLS, resolutions=[RESOLUTION]):
            try:
                # Log candle data
                symbol = candle.get("symbol", "UNKNOWN")
                resolution = candle.get("resolution", "UNKNOWN")
                open_price = candle.get("open", 0.0)
                high = candle.get("high", 0.0)
                low = candle.get("low", 0.0)
                close = candle.get("close", 0.0)
                volume = candle.get("volume", 0.0)
                timestamp = candle.get("timestamp", 0)
                
                logger.info(f"{symbol} | {resolution} | "
                      f"O:{open_price:.2f} H:{high:.2f} L:{low:.2f} C:{close:.2f} | "
                      f"V:{volume:.2f} | TS:{timestamp}")
                
                # Feed candle to engine
                await engine.on_candle(candle)
                
                # Periodically print statistics
                current_time = time.time()
                if current_time - last_stats_print >= stats_interval:
                    logger.info(f"Periodic update ({stats_interval // 60} min interval):")
                    stats = engine.get_stats()
                    logger.info(f"Summary - Total Trades: {stats['summary']['total_trades']} | "
                                f"Wins: {stats['summary']['total_wins']} | "
                                f"Losses: {stats['summary']['total_losses']} | "
                                f"P&L: ${stats['summary']['total_pnl']:.2f} | "
                                f"Win Rate: {stats['summary']['win_rate']:.2f}%")
                    logger.info(f"Current Balance: ${broker.balance:.2f}")
                    last_stats_print = current_time
                    
            except Exception as e:
                symbol = candle.get("symbol", "UNKNOWN")
                logger.error(f"Failed to process candle for {symbol}: {e}", exc_info=True)
                continue
    
    except KeyboardInterrupt:
        signal_handler(None, None)
    
    except Exception as e:
        logger.error(f"Fatal error: {e}", exc_info=True)
        sys.exit(1)
    
    finally:
        if broker:
            logger.info("=" * 80)
            logger.info("FINAL STATISTICS")
            logger.info("=" * 80)
            stats = engine.get_stats()
            logger.info(f"Total Trades: {stats['summary']['total_trades']}")
            logger.info(f"Wins: {stats['summary']['total_wins']} | Losses: {stats['summary']['total_losses']}")
            logger.info(f"Win Rate: {stats['summary']['win_rate']:.2f}%")
            logger.info(f"Total P&L: ${stats['summary']['total_pnl']:.2f}")
            logger.info(f"Initial Balance: ${broker.initial_balance:.2f}")
            logger.info(f"Current Balance: ${broker.balance:.2f}")


if __name__ == "__main__":
    asyncio.run(main())
